on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

name: pkgcheck

permissions: read-all

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: ropensci-review-tools/pkgcheck-action@v1
        with:
          post-to-issue: false
